//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2017/09/10 13:07:52
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace EasyTodoCore2Asp
{
    public partial class TodoDetailDataTmp {

        public TodoDetailDataTmp()
        {
            OnCreated();
        }

        public virtual int Id
        {
            get;
            set;
        }

        public virtual int UserId
        {
            get;
            set;
        }

        public virtual int DataId
        {
            get;
            set;
        }

        public virtual string Title
        {
            get;
            set;
        }

        public virtual string Detail
        {
            get;
            set;
        }

        public virtual System.Nullable<System.DateTime> StartDate
        {
            get;
            set;
        }

        public virtual System.Nullable<System.DateTime> EndDate
        {
            get;
            set;
        }

        public virtual System.Nullable<int> State
        {
            get;
            set;
        }

        public virtual System.Nullable<int> ColorId
        {
            get;
            set;
        }
    
        #region Extensibility Method Definitions

        partial void OnCreated();
        
        #endregion
    }

}
