//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework EntityObject template.
// Code is generated on: 2017/09/10 15:00:51
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using System.Reflection;
using System.Linq.Expressions;
using System.Data.EntityClient;
using System.Data.Metadata.Edm;
using System.Data.Objects;
using System.Data.Objects.DataClasses;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata


#endregion

namespace TodoDataModel
{

    #region TodoDataEntities

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class TodoDataEntities : ObjectContext
    {
        #region Constructors

        /// <summary>
        /// Initialize a new TodoDataEntities object.
        /// </summary>
        public TodoDataEntities() : 
                base(@"name=TodoDataEntitiesConnectionString", "TodoDataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }

        /// <summary>
        /// Initializes a new TodoDataEntities object using the connection string found in the 'TodoDataEntities' section of the application configuration file.
        /// </summary>
        public TodoDataEntities(string connectionString) : 
                base(connectionString, "TodoDataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }

        /// <summary>
        /// Initialize a new TodoDataEntities object.
        /// </summary>
        public TodoDataEntities(EntityConnection connection) : base(connection, "TodoDataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }

        #endregion

        #region Partial Methods

        partial void OnContextCreated();

        #endregion

        #region ObjectSet Properties

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TodoDetailData> TodoDetailDatas
        {
            get
            {
                if ((_TodoDetailDatas == null))
                {
                    _TodoDetailDatas = base.CreateObjectSet<TodoDetailData>("TodoDetailDatas");
                }
                return _TodoDetailDatas;
            }
        }
        private ObjectSet<TodoDetailData> _TodoDetailDatas;

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TodoDetailDataTmp> TodoDetailDataTmps
        {
            get
            {
                if ((_TodoDetailDataTmps == null))
                {
                    _TodoDetailDataTmps = base.CreateObjectSet<TodoDetailDataTmp>("TodoDetailDataTmps");
                }
                return _TodoDetailDataTmps;
            }
        }
        private ObjectSet<TodoDetailDataTmp> _TodoDetailDataTmps;

        #endregion
        #region AddTo Methods

        /// <summary>
        /// Deprecated Method for adding a new object to the TodoDetailDatas EntitySet.
        /// </summary>
        public void AddToTodoDetailDatas(TodoDetailData todoDetailData)
        {
            base.AddObject("TodoDetailDatas", todoDetailData);
        }

        /// <summary>
        /// Deprecated Method for adding a new object to the TodoDetailDataTmps EntitySet.
        /// </summary>
        public void AddToTodoDetailDataTmps(TodoDetailDataTmp todoDetailDataTmp)
        {
            base.AddObject("TodoDetailDataTmps", todoDetailDataTmp);
        }

        #endregion
    }

    #endregion
}

namespace TodoDataModel
{

    /// <summary>
    /// There are no comments for TodoDataModel.TodoDetailData in the schema.
    /// </summary>
    /// <KeyProperties>
    /// UserId
    /// DataId
    /// </KeyProperties>
    [EdmEntityTypeAttribute(NamespaceName="TodoDataModel", Name="TodoDetailData")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TodoDetailData : EntityObject    {
        #region Factory Method

        /// <summary>
        /// Create a new TodoDetailData object.
        /// </summary>
        /// <param name="userId">Initial value of UserId.</param>
        /// <param name="dataId">Initial value of DataId.</param>
        public static TodoDetailData CreateTodoDetailData(int userId, int dataId)
        {
            TodoDetailData todoDetailData = new TodoDetailData();
            todoDetailData.UserId = userId;
            todoDetailData.DataId = dataId;
            return todoDetailData;
        }

        #endregion

        #region Properties
    
        /// <summary>
        /// There are no comments for UserId in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public virtual int UserId
        {
            get
            {
                int value = _UserId;
                OnGetUserId(ref value);
                return value;
            }
            set
            {
                if (_UserId != value)
                {
                  OnUserIdChanging(ref value);
                  ReportPropertyChanging("UserId");
                  _UserId = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("UserId");
                  OnUserIdChanged();
              }
            }
        }
        private int _UserId;
        partial void OnGetUserId(ref int value);
        partial void OnUserIdChanging(ref int value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// There are no comments for DataId in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public virtual int DataId
        {
            get
            {
                int value = _DataId;
                OnGetDataId(ref value);
                return value;
            }
            set
            {
                if (_DataId != value)
                {
                  OnDataIdChanging(ref value);
                  ReportPropertyChanging("DataId");
                  _DataId = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("DataId");
                  OnDataIdChanged();
              }
            }
        }
        private int _DataId;
        partial void OnGetDataId(ref int value);
        partial void OnDataIdChanging(ref int value);
        partial void OnDataIdChanged();
    
        /// <summary>
        /// There are no comments for Title in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public virtual string Title
        {
            get
            {
                string value = _Title;
                OnGetTitle(ref value);
                return value;
            }
            set
            {
                if (_Title != value)
                {
                  OnTitleChanging(ref value);
                  ReportPropertyChanging("Title");
                  _Title = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("Title");
                  OnTitleChanged();
              }
            }
        }
        private string _Title;
        partial void OnGetTitle(ref string value);
        partial void OnTitleChanging(ref string value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// There are no comments for Detail in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public virtual string Detail
        {
            get
            {
                string value = _Detail;
                OnGetDetail(ref value);
                return value;
            }
            set
            {
                if (_Detail != value)
                {
                  OnDetailChanging(ref value);
                  ReportPropertyChanging("Detail");
                  _Detail = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("Detail");
                  OnDetailChanged();
              }
            }
        }
        private string _Detail;
        partial void OnGetDetail(ref string value);
        partial void OnDetailChanging(ref string value);
        partial void OnDetailChanged();
    
        /// <summary>
        /// There are no comments for StartDate in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public virtual global::System.Nullable<System.DateTime> StartDate
        {
            get
            {
                global::System.Nullable<System.DateTime> value = _StartDate;
                OnGetStartDate(ref value);
                return value;
            }
            set
            {
                if (_StartDate != value)
                {
                  OnStartDateChanging(ref value);
                  ReportPropertyChanging("StartDate");
                  _StartDate = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("StartDate");
                  OnStartDateChanged();
              }
            }
        }
        private global::System.Nullable<System.DateTime> _StartDate;
        partial void OnGetStartDate(ref global::System.Nullable<System.DateTime> value);
        partial void OnStartDateChanging(ref global::System.Nullable<System.DateTime> value);
        partial void OnStartDateChanged();
    
        /// <summary>
        /// There are no comments for EndDate in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public virtual global::System.Nullable<System.DateTime> EndDate
        {
            get
            {
                global::System.Nullable<System.DateTime> value = _EndDate;
                OnGetEndDate(ref value);
                return value;
            }
            set
            {
                if (_EndDate != value)
                {
                  OnEndDateChanging(ref value);
                  ReportPropertyChanging("EndDate");
                  _EndDate = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("EndDate");
                  OnEndDateChanged();
              }
            }
        }
        private global::System.Nullable<System.DateTime> _EndDate;
        partial void OnGetEndDate(ref global::System.Nullable<System.DateTime> value);
        partial void OnEndDateChanging(ref global::System.Nullable<System.DateTime> value);
        partial void OnEndDateChanged();
    
        /// <summary>
        /// There are no comments for State in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public virtual global::System.Nullable<int> State
        {
            get
            {
                global::System.Nullable<int> value = _State;
                OnGetState(ref value);
                return value;
            }
            set
            {
                if (_State != value)
                {
                  OnStateChanging(ref value);
                  ReportPropertyChanging("State");
                  _State = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("State");
                  OnStateChanged();
              }
            }
        }
        private global::System.Nullable<int> _State;
        partial void OnGetState(ref global::System.Nullable<int> value);
        partial void OnStateChanging(ref global::System.Nullable<int> value);
        partial void OnStateChanged();
    
        /// <summary>
        /// There are no comments for ColorId in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public virtual global::System.Nullable<int> ColorId
        {
            get
            {
                global::System.Nullable<int> value = _ColorId;
                OnGetColorId(ref value);
                return value;
            }
            set
            {
                if (_ColorId != value)
                {
                  OnColorIdChanging(ref value);
                  ReportPropertyChanging("ColorId");
                  _ColorId = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("ColorId");
                  OnColorIdChanged();
              }
            }
        }
        private global::System.Nullable<int> _ColorId;
        partial void OnGetColorId(ref global::System.Nullable<int> value);
        partial void OnColorIdChanging(ref global::System.Nullable<int> value);
        partial void OnColorIdChanged();

        #endregion
    }

    /// <summary>
    /// There are no comments for TodoDataModel.TodoDetailDataTmp in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [EdmEntityTypeAttribute(NamespaceName="TodoDataModel", Name="TodoDetailDataTmp")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TodoDetailDataTmp : EntityObject    {
        #region Factory Method

        /// <summary>
        /// Create a new TodoDetailDataTmp object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="userId">Initial value of UserId.</param>
        /// <param name="dataId">Initial value of DataId.</param>
        public static TodoDetailDataTmp CreateTodoDetailDataTmp(int id, int userId, int dataId)
        {
            TodoDetailDataTmp todoDetailDataTmp = new TodoDetailDataTmp();
            todoDetailDataTmp.Id = id;
            todoDetailDataTmp.UserId = userId;
            todoDetailDataTmp.DataId = dataId;
            return todoDetailDataTmp;
        }

        #endregion

        #region Properties
    
        /// <summary>
        /// There are no comments for Id in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public virtual int Id
        {
            get
            {
                int value = _Id;
                OnGetId(ref value);
                return value;
            }
            set
            {
                if (_Id != value)
                {
                  OnIdChanging(ref value);
                  ReportPropertyChanging("Id");
                  _Id = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("Id");
                  OnIdChanged();
              }
            }
        }
        private int _Id;
        partial void OnGetId(ref int value);
        partial void OnIdChanging(ref int value);
        partial void OnIdChanged();
    
        /// <summary>
        /// There are no comments for UserId in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute(IsNullable=false)]
        [DataMemberAttribute()]
        public virtual int UserId
        {
            get
            {
                int value = _UserId;
                OnGetUserId(ref value);
                return value;
            }
            set
            {
                if (_UserId != value)
                {
                  OnUserIdChanging(ref value);
                  ReportPropertyChanging("UserId");
                  _UserId = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("UserId");
                  OnUserIdChanged();
              }
            }
        }
        private int _UserId;
        partial void OnGetUserId(ref int value);
        partial void OnUserIdChanging(ref int value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// There are no comments for DataId in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute(IsNullable=false)]
        [DataMemberAttribute()]
        public virtual int DataId
        {
            get
            {
                int value = _DataId;
                OnGetDataId(ref value);
                return value;
            }
            set
            {
                if (_DataId != value)
                {
                  OnDataIdChanging(ref value);
                  ReportPropertyChanging("DataId");
                  _DataId = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("DataId");
                  OnDataIdChanged();
              }
            }
        }
        private int _DataId;
        partial void OnGetDataId(ref int value);
        partial void OnDataIdChanging(ref int value);
        partial void OnDataIdChanged();
    
        /// <summary>
        /// There are no comments for Title in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public virtual string Title
        {
            get
            {
                string value = _Title;
                OnGetTitle(ref value);
                return value;
            }
            set
            {
                if (_Title != value)
                {
                  OnTitleChanging(ref value);
                  ReportPropertyChanging("Title");
                  _Title = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("Title");
                  OnTitleChanged();
              }
            }
        }
        private string _Title;
        partial void OnGetTitle(ref string value);
        partial void OnTitleChanging(ref string value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// There are no comments for Detail in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public virtual string Detail
        {
            get
            {
                string value = _Detail;
                OnGetDetail(ref value);
                return value;
            }
            set
            {
                if (_Detail != value)
                {
                  OnDetailChanging(ref value);
                  ReportPropertyChanging("Detail");
                  _Detail = StructuralObject.SetValidValue(value, true);
                  ReportPropertyChanged("Detail");
                  OnDetailChanged();
              }
            }
        }
        private string _Detail;
        partial void OnGetDetail(ref string value);
        partial void OnDetailChanging(ref string value);
        partial void OnDetailChanged();
    
        /// <summary>
        /// There are no comments for StartDate in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public virtual global::System.Nullable<System.DateTime> StartDate
        {
            get
            {
                global::System.Nullable<System.DateTime> value = _StartDate;
                OnGetStartDate(ref value);
                return value;
            }
            set
            {
                if (_StartDate != value)
                {
                  OnStartDateChanging(ref value);
                  ReportPropertyChanging("StartDate");
                  _StartDate = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("StartDate");
                  OnStartDateChanged();
              }
            }
        }
        private global::System.Nullable<System.DateTime> _StartDate;
        partial void OnGetStartDate(ref global::System.Nullable<System.DateTime> value);
        partial void OnStartDateChanging(ref global::System.Nullable<System.DateTime> value);
        partial void OnStartDateChanged();
    
        /// <summary>
        /// There are no comments for EndDate in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public virtual global::System.Nullable<System.DateTime> EndDate
        {
            get
            {
                global::System.Nullable<System.DateTime> value = _EndDate;
                OnGetEndDate(ref value);
                return value;
            }
            set
            {
                if (_EndDate != value)
                {
                  OnEndDateChanging(ref value);
                  ReportPropertyChanging("EndDate");
                  _EndDate = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("EndDate");
                  OnEndDateChanged();
              }
            }
        }
        private global::System.Nullable<System.DateTime> _EndDate;
        partial void OnGetEndDate(ref global::System.Nullable<System.DateTime> value);
        partial void OnEndDateChanging(ref global::System.Nullable<System.DateTime> value);
        partial void OnEndDateChanged();
    
        /// <summary>
        /// There are no comments for State in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public virtual global::System.Nullable<int> State
        {
            get
            {
                global::System.Nullable<int> value = _State;
                OnGetState(ref value);
                return value;
            }
            set
            {
                if (_State != value)
                {
                  OnStateChanging(ref value);
                  ReportPropertyChanging("State");
                  _State = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("State");
                  OnStateChanged();
              }
            }
        }
        private global::System.Nullable<int> _State;
        partial void OnGetState(ref global::System.Nullable<int> value);
        partial void OnStateChanging(ref global::System.Nullable<int> value);
        partial void OnStateChanged();
    
        /// <summary>
        /// There are no comments for ColorId in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute()]
        [DataMemberAttribute()]
        public virtual global::System.Nullable<int> ColorId
        {
            get
            {
                global::System.Nullable<int> value = _ColorId;
                OnGetColorId(ref value);
                return value;
            }
            set
            {
                if (_ColorId != value)
                {
                  OnColorIdChanging(ref value);
                  ReportPropertyChanging("ColorId");
                  _ColorId = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("ColorId");
                  OnColorIdChanged();
              }
            }
        }
        private global::System.Nullable<int> _ColorId;
        partial void OnGetColorId(ref global::System.Nullable<int> value);
        partial void OnColorIdChanging(ref global::System.Nullable<int> value);
        partial void OnColorIdChanged();

        #endregion
    }

}
